-- AlterTable
ALTER TABLE "Room" ADD COLUMN     "Avarage_Rating" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Total_Rating" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Users_Rating" INTEGER NOT NULL DEFAULT 0;
